#!/usr/bin/env python
# -*- coding: utf8 -*-
from __future__ import print_function
import argparse
import errno
import os
import re
import sys


# Monkey-patch argparse so that we can have a default subparse
# Source: # https://stackoverflow.com/questions/6365601/
#       default-sub-command-or-handling-no-sub-command-with-argparse
def set_default_subparser(self, name, args=None):
    """default subparser selection. Call after setup, just before parse_args()
    name: is the name of the subparser to call by default
    args: if set is the argument list handed to parse_args()

    , tested with 2.7, 3.2, 3.3, 3.4
    it works with 2.6 assuming argparse is installed
    """
    subparser_found = False
    for arg in sys.argv[1:]:
        if arg in ['-h', '--help']:  # global help if no subparser
            break
    else:
        for x in self._subparsers._actions:
            if not isinstance(x, argparse._SubParsersAction):
                continue
            for sp_name in x._name_parser_map.keys():
                if sp_name in sys.argv[1:]:
                    subparser_found = True
        if not subparser_found:
            # insert default in first position, this implies no
            # global options without a sub_parsers specified
            if args is None:
                sys.argv.insert(1, name)
            else:
                args.insert(0, name)

argparse.ArgumentParser.set_default_subparser = set_default_subparser

IGNORE_DIRS = ['.git']
IGNORE_SUFFIXES = ['.swp']
SOURCE = os.path.expanduser('~/.simpledot')
RE_DOTFILE = re.compile('dotfile\s+@\s+(.*)')

COLOR_PREFIX = '\033['
COLOR_RED = '31m'
COLOR_GREEN = '32m'
COLOR_YELLOW = '33m'
COLOR_RESET = '0m'


def colorize(s, color=None):
    if not color:
        return s

    constname = 'COLOR_{}'.format(color.upper())
    try:
        color = globals()[constname]
    except KeyError:
        print("error: unknown color '{}'".format(color), file=sys.stderr)
        return s

    return u''.join([COLOR_PREFIX, color, s, COLOR_PREFIX, COLOR_RESET])


def checkmark(checked):
    if checked:
        return colorize(u'✓', color='green')
    else:
        return colorize(u'✗', color='red')


def warn(s):
    print(colorize(u"warning: {}".format(s), color='yellow'),
          file=sys.stderr)


def cmd_source(args):
    path = os.path.expanduser(args.path)
    path = os.path.abspath(path)
    if not os.path.exists(path):
        sys.exit("error: '{}' not found".format(path))

    if os.path.exists(SOURCE):
        sys.exit("error: '{}' already exists, delete it if you'd like to add"
                 " a different source".format(SOURCE))

    os.symlink(path, SOURCE)


def yield_annotations():
    if not os.path.exists(SOURCE):
        sys.exit("error: no sources, first use 'source' to add a directory")
    for root, dirnames, filenames in os.walk(SOURCE, topdown=True):
        # In-place modify dirnames to tell `walk()` to skip these directories
        # Requires `topdown=True` to work.
        for dirname in IGNORE_DIRS:
            dirnames.remove(dirname)
        for filename in filenames:
            ignore = False
            for suffix in IGNORE_SUFFIXES:
                if filename.endswith(suffix):
                    ignore = True
                    break
            if ignore:
                continue
            src = os.path.join(root, filename)
            with open(src) as f:
                match = RE_DOTFILE.search(f.read())
                if match:
                    dst =  match.group(1).strip()
                    dst = os.path.expanduser(dst)
                    yield src, dst


def cmd_list(args):
    print("Source: {}\n".format(SOURCE))
    for src, dst in sorted(yield_annotations()):
        relsrc = os.path.relpath(src, SOURCE)
        exists = os.path.exists(dst)
        print(u"{} {:20} -> {}".format(checkmark(exists), relsrc, dst))


def cmd_up(args):
    for src, dst in yield_annotations():
        if not os.path.exists(src):
            warn("source file '{}' does not exist".format(src))
            continue
        if os.path.islink(src):
            warn("source file '{}' is a symbolic link".format(src))
            continue
        if os.path.exists(dst):
            warn("'{}' already exists".format(dst))
            continue

        dst_dirname = os.path.dirname(dst)
        try:
            os.makedirs(dst_dirname)
        except OSError as e:
            if e.errno != errno.EEXIST:
                raise
        os.symlink(src, dst)


def cmd_down(args):
    for src, dst in yield_annotations():
        if not os.path.exists(dst):
            warn("'{}' does not exist".format(dst))
            continue
        if not os.path.islink(dst):
            warn("'{}' is not a symbolic link".format(dst))
            continue
        os.unlink(dst)


def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()

    source_parser = subparsers.add_parser('list')
    source_parser.set_defaults(func=cmd_list)

    source_parser = subparsers.add_parser('source')
    source_parser.add_argument('path')
    source_parser.set_defaults(func=cmd_source)

    source_parser = subparsers.add_parser('up')
    source_parser.set_defaults(func=cmd_up)

    source_parser = subparsers.add_parser('down')
    source_parser.set_defaults(func=cmd_down)

    parser.set_default_subparser('list')

    args = parser.parse_args()
    return args.func(args)


if __name__ == '__main__':
    main()
